version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn workspace frontend start
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:4000
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn workspace backend start
    ports:
      - "4000:4000"
    restart: always
    environment:
      - PORT=4000
      - CLIENT_URL=http://localhost:3000
    networks:
      - app-net

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma:/app/data
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

volumes:
  uptime-kuma:

networks:
  app-net:
