version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    restart: always
    environment:
      - PORT=3001
      - CLIENT_URL=https://metapick.site
    networks:
      - app-net

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - "4000:3001"
    volumes:
      - uptime-kuma:/app/data
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

volumes:
  uptime-kuma:

networks:
  app-net:
