version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:3001
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    restart: always
    environment:
      - PORT=3001
      - CLIENT_URL=http://frontend:3000
    networks:
      - app-net

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - "4000:3001"
    volumes:
      - uptime-kuma:/app/data
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - uptime-kuma

volumes:
  uptime-kuma:

networks:
  app-net:
