version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn workspace frontend start
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:4000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn workspace backend start
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CLIENT_URL=http://localhost:3000
